// AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand.
// Source of truth is src/tokens/*.css. Values that are CSS var() references
// (semantic aliases) are exported as their literal var() string, not resolved.

export const nyxcColorBrandCream = "#eed7b3";
export const nyxcColorBrandCreamTransparent = "rgba(238, 215, 179, 0.02)";
export const nyxcColorBrandCreamInvisible = "rgba(238, 215, 179, 0)";
export const nyxcColorBrandMint = "#d2ffe7";
export const nyxcColorBrandMintSoft = "rgba(210, 255, 231, 0.8)";
export const nyxcColorWhite = "#fff";
export const nyxcColorNeutral100 = "#d9d9d9";
export const nyxcColorInk = "#090012";
export const nyxcColorBgBase = "#10031d";
export const nyxcColorSurface = "var(--nyxc-color-bg-base)";
export const nyxcColorTextPrimary = "var(--nyxc-color-white)";
export const nyxcColorTextInverse = "var(--nyxc-color-ink)";
export const nyxcColorAccent = "var(--nyxc-color-brand-cream)";
export const nyxcColorAccentSoft = "var(--nyxc-color-brand-mint)";
export const nyxcColorBorder = "var(--nyxc-color-neutral-100)";
export const nyxcFontFamilyBase = "\"ITC Avant Garde Gothic Std\", sans-serif";
export const nyxcFontSize100 = "14px";
export const nyxcFontSize200 = "15px";
export const nyxcFontSize300 = "20px";
export const nyxcFontSize400 = "30px";
export const nyxcFontSize500 = "60px";
export const nyxcFontWeightBook = "400";
export const nyxcFontWeightMedium = "500";
export const nyxcFontWeightDemi = "600";
export const nyxcFontWeightBold = "700";
export const nyxcLineHeightNormal = "normal";
export const nyxcLineHeightTight = "1.1";
export const nyxcSpace1 = "4px";
export const nyxcSpace2 = "8px";
export const nyxcSpace3 = "12px";
export const nyxcSpace4 = "16px";
export const nyxcSpace5 = "24px";
export const nyxcSpace6 = "32px";
export const nyxcSpace7 = "48px";
export const nyxcSpace8 = "64px";
export const nyxcRadiusSm = "10px";
export const nyxcRadiusMd = "20px";
export const nyxcRadiusXl = "80px";

export const tokens = {
  "nyxc-color-brand-cream": "#eed7b3",
  "nyxc-color-brand-cream-transparent": "rgba(238, 215, 179, 0.02)",
  "nyxc-color-brand-cream-invisible": "rgba(238, 215, 179, 0)",
  "nyxc-color-brand-mint": "#d2ffe7",
  "nyxc-color-brand-mint-soft": "rgba(210, 255, 231, 0.8)",
  "nyxc-color-white": "#fff",
  "nyxc-color-neutral-100": "#d9d9d9",
  "nyxc-color-ink": "#090012",
  "nyxc-color-bg-base": "#10031d",
  "nyxc-color-surface": "var(--nyxc-color-bg-base)",
  "nyxc-color-text-primary": "var(--nyxc-color-white)",
  "nyxc-color-text-inverse": "var(--nyxc-color-ink)",
  "nyxc-color-accent": "var(--nyxc-color-brand-cream)",
  "nyxc-color-accent-soft": "var(--nyxc-color-brand-mint)",
  "nyxc-color-border": "var(--nyxc-color-neutral-100)",
  "nyxc-font-family-base": "\"ITC Avant Garde Gothic Std\", sans-serif",
  "nyxc-font-size-100": "14px",
  "nyxc-font-size-200": "15px",
  "nyxc-font-size-300": "20px",
  "nyxc-font-size-400": "30px",
  "nyxc-font-size-500": "60px",
  "nyxc-font-weight-book": "400",
  "nyxc-font-weight-medium": "500",
  "nyxc-font-weight-demi": "600",
  "nyxc-font-weight-bold": "700",
  "nyxc-line-height-normal": "normal",
  "nyxc-line-height-tight": "1.1",
  "nyxc-space-1": "4px",
  "nyxc-space-2": "8px",
  "nyxc-space-3": "12px",
  "nyxc-space-4": "16px",
  "nyxc-space-5": "24px",
  "nyxc-space-6": "32px",
  "nyxc-space-7": "48px",
  "nyxc-space-8": "64px",
  "nyxc-radius-sm": "10px",
  "nyxc-radius-md": "20px",
  "nyxc-radius-xl": "80px",
} as const;

export type TokenName = keyof typeof tokens;
