// Parses src/tokens/*.css custom properties into src/tokens/tokens.ts.
// The CSS files stay the single source of truth; this script keeps the
// generated TS in sync with them on every build.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const tokensDir = join(__dirname, "..", "src", "tokens");
const files = ["colors.css", "typography.css", "spacing.css"];

const DECL_RE = /--(nyxc-[a-z0-9-]+)\s*:\s*([^;]+);/g;

function toCamelCase(kebab) {
  return kebab.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

const entries = [];
for (const file of files) {
  const css = readFileSync(join(tokensDir, file), "utf8");
  for (const match of css.matchAll(DECL_RE)) {
    const [, name, rawValue] = match;
    entries.push({ name, value: rawValue.trim() });
  }
}

const seen = new Set();
const uniqueEntries = entries.filter((e) => {
  if (seen.has(e.name)) return false;
  seen.add(e.name);
  return true;
});

const constLines = uniqueEntries
  .map((e) => `export const ${toCamelCase(e.name)} = ${JSON.stringify(e.value)};`)
  .join("\n");

const namespacedLines = uniqueEntries
  .map((e) => `  "${e.name}": ${JSON.stringify(e.value)},`)
  .join("\n");

const output = `// AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand.
// Source of truth is src/tokens/*.css. Values that are CSS var() references
// (semantic aliases) are exported as their literal var() string, not resolved.

${constLines}

export const tokens = {
${namespacedLines}
} as const;

export type TokenName = keyof typeof tokens;
`;

writeFileSync(join(tokensDir, "tokens.ts"), output);
console.log(`Generated tokens.ts with ${uniqueEntries.length} tokens.`);
